# The Docker Config version. Do not change.
version: "3.1"
services:
  ui:
    image: ui-image
    container_name: ui
    volumes:
      - "./client:/app"
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - server

  server:
    image: server
    container_name: server
    volumes:
      - "./server:/app"
    ports:
      - "3001:3001"
    networks:
      - app-network
    environment:
      DB_CONNECTION_STRING: postgres://postgres:password@db:5432/db
    depends_on:
      - db

  db:
    image: db
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db

    volumes:
      - ./my_data_directory:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge