/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  // Deletes ALL existing entries
  await knex("report_template").del();
  await knex("report_template").insert([
    /*WGS 24 Hour Report*/ {
      id: 0,
      report_name: "WGS 24 Hour Report",
      date: true,
      unit: true,
      team_name: true,
      mission_number: true,
      satellite_name: true,
      norad_id: true,
      tpo: true,
      ebno: true,
      ber: true,
      location: true,
      pim: true,
      weather: true,
      event: false,
      terminal: true,
      opscap: false,
      syscap: false,
      hazcon: true,
      comments: true,
      username: true,
      phone: true,
      email: true,
      chops: true,
    },
    /*GPS report*/{
      id: 1,
      report_name: "GPS log",
      date: true,
      unit: true,
      team_name: true,
      mission_number: true,
      satellite_name: true,
      norad_id: true,
      tpo: false,
      ebno: false,
      ber: true,
      location: true,
      pim: false,
      weather: true,
      event: false,
      terminal: false,
      opscap: false,
      syscap: false,
      hazcon: false,
      comments: true,
      username: true,
      phone: true,
      email: true,
      chops: true,
    },
    /*CCS report*/{
      id: 2,
      report_name: "CCS report",
      date: true,
      unit: true,
      team_name: true,
      mission_number: true,
      satellite_name: true,
      norad_id: false,
      tpo: false,
      ebno: true,
      ber: true,
      location: true,
      pim: false,
      weather: false,
      event: true,
      terminal: false,
      opscap: true,
      syscap: false,
      hazcon: true,
      comments: true,
      username: true,
      phone: true,
      email: true,
      chops: true,
    }
  ]);
};
