/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function(knex) {
  // Deletes ALL existing entries
  await knex('report_data').del()
  await knex('report_data').insert([
    /*WGS 24 Hour Report*/ {
      id: 0,
      report_name: "WGS 24 Hour Report",  // date: Autopopulated,
      unit: '53 SOPS',
      team_name: 'da boyz',
      mission_number: '2487ax3',
      satellite_id: 3,
      tpo: 1231123.87234,
      'eb-no': 0.5,
      ber: 0.0012,
      latitude: '10.1 N',
      longitude: '10.1 E',
      pim: '1320 lat: 11.1 W long: 12.1 E',
      weather: 'sunny day',
      event: null,
      terminal: 'antxc156b',
      opscap: null,
      syscap: null,
      hazcon: 'shit everywhere',
      comments: 'please clean up this shit',
      user_id: 1,
    },
    /*CCS Report*/ {
      id: 1,
      report_name: "CCS log",  // date: Autopopulated,
      unit: '4 EWS',
      team_name: 'da better boyz',
      mission_number: '32967',
      satellite_id: 5,
      tpo: null,
      'eb-no': 0.5,
      ber: 0.0012,
      latitude: '58.9 N' ,
      longitude: '76.4 W',
      pim: null,
      weather: 'cloudy with a chance of meatballs',
      event: 'we did real nice',
      opscap: 'GREEN',
      syscap: 'GREEN',
      hazcon: 'shit everywhere here too',
      comments: 'please clean up everyones shit',
      user_id: 3
    },
    /*GPS Report*/ {
      id: 2,
      report_name: "GPS log",  // date: Autopopulated,
      unit: '2 SOPS',
      team_name: 'da sad boyz',
      mission_number: '420',
      satellite_id: 6,
      tpo: null,
      'eb-no': null,
      ber: 0.0012,
      latitude: '87.3 N' ,
      longitude: '.021 E',
      pim: null,
      weather: 'rainy day',
      event: null,
      terminal: null,
      opscap: null,
      syscap: null,
      hazcon: 'shit...',
      comments: 'why cant anyone get their shit cleaned up?',
      user_id: 2,
    },
    /*WGS 24 Hour Report*/ {
      id: 3,
      report_name: "WGS 24 Hour Report",  // date: Autopopulated,
      unit: '53 SOPS',
      team_name: 'da boyz',
      mission_number: '9283408',
      satellite_id: 2,
      tpo: 987435.3094123,
      'eb-no': 0.4,
      ber: 0.0104,
      latitude: '64.2 N',
      longitude: '13.3 E',
      pim: '1320 lat: 11.1 W long: 12.1 E',
      weather: 'suns out guns out',
      event: null,
      terminal: '928731ux',
      opscap: null,
      syscap: null,
      hazcon: 'We caught the shit',
      comments: 'send help',
      user_id: 1,
    },
    /*CCS Report*/ {
      id: 4,
      report_name: "CCS log",  // date: Autopopulated,
      unit: '4 EWS',
      team_name: 'da better boyz',
      mission_number: '32967',
      satellite_id: 5,
      tpo: null,
      'eb-no': 0.5,
      ber: 0.0012,
      latitude: '58.9 N' ,
      longitude: '76.4 W',
      pim: null,
      weather: 'cloudy with a chance of meatballs',
      event: 'we did real nice',
      opscap: 'GREEN',
      syscap: 'GREEN',
      hazcon: 'shit everywhere here too',
      comments: 'please clean up everyones shit',
      user_id: 3
    },
    /*GPS Report*/ {
      id: 5,
      report_name: "GPS log",  // date: Autopopulated,
      unit: '2 SOPS',
      team_name: 'da sad boyz',
      mission_number: '420-1',
      satellite_id: 7,
      tpo: null,
      'eb-no': null,
      ber: 1,
      latitude: '69.3 N' ,
      longitude: '69.3 E',
      pim: null,
      weather: 'gonna be a bright sunny day',
      event: null,
      terminal: null,
      opscap: null,
      syscap: null,
      hazcon: 'good shit',
      comments: 'finnaly something good',
      user_id: 2,
    }
  ]);
};